### ISSUE TITLE
Day 38 Lab - AddReminderViewController not working properly

### ISSUE THREAD

**Issue by elaewin** [thegrimheep/location-reminders#11]
It looks like there is some default implementation in `ViewDidLoad` on your `AddReminderViewController` that is preventing a user from giving new reminders a location and radius. When I click on the `New Location` after dropping a pin, it segues properly, then immediately closes the `AddReminderViewController` and puts a new overlay on the map.

**Comment by thegrimheep** [comment]
I have this issue corrected, thank you for bringing it to my attention.
